services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStr0ngP@ssword
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ecommerce-net

  product-api:
    image: cabtaindeptrai/commandservice:latest
    container_name: product-api
    depends_on:
      - sqlserver
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__eCommerceConnection=Server=sqlserver;Database=EcommerceDb;User Id=sa;Password=YourStr0ngP@ssword;TrustServerCertificate=true;
    networks:
      - ecommerce-net

volumes:
  sqlserver_data:

networks:
  ecommerce-net:
    driver: bridge
